In [1]:
import torch

In [5]:
"""
Multiples an input by the kernel (1 channel)
X: input
K: kernel

"""
def corr2d(X, K):
    h, w = K.shape
    # this is a formula to calculate the output 
    feature_map = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    # fill each number in the output with element-wise multiplication
    for i in range(output.shape[0]):
        for j in range(output.shape[1]):
            input_to_multiply = X[i:i+h, j:j+w]
            feature_map[i, j] = (input_to_multiply * K).sum()
    return feature_map

In [6]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
corr2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

In [9]:
"""
a convolutional layer performs corr2d and adds in the bias term
kernel size: shape of the kernel
"""
class Conv2D(nn.Module):
    def __init__(self, kernel_size):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(kernel_size))
        self.bias = nn.Parameter(torch.rand(torch.zeros(1))
                             
    def forward(self, x):
        return corr2d(x, self.weight) + self.bias 

tensor([0.])

In [10]:
"""
Multiples an input by the kernel (multi channel)
X: input
K: kernel

"""
def corr2d_multi_in(X, K):
    # multiplies each channel by a kernel, then sums up the results so we end up with one channel
    return sum(corr2d(x, k) for x, k in zip(X, K))

X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [15]:
[k.shape for k in K]

[torch.Size([2, 2]), torch.Size([2, 2])]